# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vicenteg
email: vince@vincegonzalez.dev
description: > # this means to ignore newlines until "baseurl:"
  Things I decided to write about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vicenteg.github.io" # the base hostname & protocol for your site
twitter_username: ecnivny
github_username:  vicenteg

# Build settings
markdown: kramdown
kramdown:
  input: GFM
